### ISSUE TITLE
Unable to create account

### ISSUE THREAD

**Issue by jimenezfer** [dsound/dsound#10]
Hi, when I try to login to dsound , my login button appear gray out (login and logout of my steemit account), I wanted to create an account to engage with an artist to ask him how could I get the full file of one of his tracks , cuz it always stucks in an specific minute(file is 1:10 or so), am reviewing ipfs documentation to see how this problem could be fix. 

Thank you for this awesome tool.

Cheers!

**Comment by prcolaco** [comment]
Account creation is handled by Steemit.com at the moment. Playback had many improvements on the last version. Thanks.

**Comment by jimenezfer** [comment]
There was a song, that was not replicated a lot by peers(my guess), I really wanted to listen to it , but download and playing didnt last long(song was like an hour), is there a way to support the network in order to allow a file like this to actually spread and be shareable?

Thanks for your attention, Dsound kicks ass!
